/* ============================================================
   DOMINIC PRO TOOLS — Master Product Catalogue
   ============================================================ */

window.DPT_BASE_PRODUCTS = [
  // ── POWER TOOLS ──────────────────────────────────────────
  { id:1,  name:'DEWALT Cordless Brushless Rotary Hammer', brand:'DEWALT',  category:'power',       categoryLabel:'POWER TOOLS',          price:105000, oldPrice:120000, discount:13, image:'DOMINIC TOOLS/POWER TOOLS/Rotary Hammer drill kit.png',                 stock:10, active:true, order:1  },
  { id:2,  name:'MAXMECH 950W Angle Grinder',              brand:'MAXMECH', category:'power',       categoryLabel:'POWER TOOLS',          price:25000,  oldPrice:30000,  discount:17, image:'DOMINIC TOOLS/POWER TOOLS/maxmech 950w grinder .png',                  stock:15, active:true, order:2  },
  { id:3,  name:'MAXMECH 1400W Circular Saw',              brand:'MAXMECH', category:'power',       categoryLabel:'POWER TOOLS',          price:60000,  oldPrice:70000,  discount:14, image:'DOMINIC TOOLS/POWER TOOLS/Maxmech 1400w Circular saw.png',             stock:8,  active:true, order:3  },
  { id:4,  name:'TOTAL Cordless Drill 55N.M',              brand:'TOTAL',   category:'power',       categoryLabel:'POWER TOOLS',          price:80000,  oldPrice:88000,  discount:9,  image:'DOMINIC TOOLS/POWER TOOLS/Total Cordless Drill.png',                   stock:12, active:true, order:4  },
  { id:5,  name:'BOSCH GSR120-LI 12V Cordless Drill',      brand:'BOSCH',   category:'power',       categoryLabel:'POWER TOOLS',          price:90000,  oldPrice:95000,  discount:5,  image:'DOMINIC TOOLS/POWER TOOLS/Original Bosch 12v.png',                     stock:7,  active:true, order:5  },
  { id:6,  name:'INGCO Cordless Brushless Drill',           brand:'INGCO',   category:'power',       categoryLabel:'POWER TOOLS',          price:75000,  oldPrice:80000,  discount:6,  image:'DOMINIC TOOLS/POWER TOOLS/Ingco cordless drill.png',                   stock:9,  active:true, order:6  },
  { id:7,  name:'TOTAL 710W Angle Grinder',                brand:'TOTAL',   category:'power',       categoryLabel:'POWER TOOLS',          price:42000,  oldPrice:48000,  discount:13, image:'DOMINIC TOOLS/POWER TOOLS/710W total grinder .png',                    stock:20, active:true, order:7  },
  { id:8,  name:'INGCO 710W Angle Grinder',                brand:'INGCO',   category:'power',       categoryLabel:'POWER TOOLS',          price:42000,  oldPrice:48000,  discount:13, image:'DOMINIC TOOLS/POWER TOOLS/710W Ingco grinder.png',                     stock:18, active:true, order:8  },
  { id:9,  name:'BOSCH GSB 183-LI 18V Cordless Impact Drill', brand:'BOSCH',category:'power',       categoryLabel:'POWER TOOLS',          price:130000, oldPrice:140000, discount:7,  image:'DOMINIC TOOLS/POWER TOOLS/Bosch 18v.png',                              stock:5,  active:true, order:9  },
  { id:10, name:'BOSCH Cordless Drill Driver Kit',          brand:'BOSCH',   category:'power',       categoryLabel:'POWER TOOLS',          price:115000, oldPrice:0,      discount:0,  image:'DOMINIC TOOLS/POWER TOOLS/Bosch cordless drill driver kit .png',       stock:6,  active:true, order:10 },
  { id:11, name:'DEWALT 4-in-1 Cordless Power Tools',      brand:'DEWALT',  category:'power',       categoryLabel:'POWER TOOLS',          price:150000, oldPrice:165000, discount:9,  image:'DOMINIC TOOLS/POWER TOOLS/4 in 1 Dewalt Cordless power tools.jpeg',    stock:4,  active:true, order:11 },
  { id:12, name:'DEWALT Cordless Angle Grinder',           brand:'DEWALT',  category:'power',       categoryLabel:'POWER TOOLS',          price:95000,  oldPrice:0,      discount:0,  image:'DOMINIC TOOLS/POWER TOOLS/Dewalt Cordless Angle Grinder.jpeg',          stock:8,  active:true, order:12 },
  { id:13, name:'INGCO 12V Drilling Machine',              brand:'INGCO',   category:'power',       categoryLabel:'POWER TOOLS',          price:65000,  oldPrice:0,      discount:0,  image:'DOMINIC TOOLS/POWER TOOLS/Ingco 12V drilling Machine.jpeg',             stock:11, active:true, order:13 },
  { id:14, name:'INGCO 2400W Angle Grinder',               brand:'INGCO',   category:'power',       categoryLabel:'POWER TOOLS',          price:55000,  oldPrice:0,      discount:0,  image:'DOMINIC TOOLS/POWER TOOLS/Ingco 2400 watts Angkle Grinder.jpeg',        stock:14, active:true, order:14 },
  { id:15, name:'INGCO Cordless Angle Grinder',            brand:'INGCO',   category:'power',       categoryLabel:'POWER TOOLS',          price:70000,  oldPrice:0,      discount:0,  image:'DOMINIC TOOLS/POWER TOOLS/Ingco Cordless Angle Grinder.jpeg',           stock:9,  active:true, order:15 },
  { id:16, name:'MAXMECH 2600W Angle Grinder',             brand:'MAXMECH', category:'power',       categoryLabel:'POWER TOOLS',          price:48000,  oldPrice:0,      discount:0,  image:'DOMINIC TOOLS/POWER TOOLS/Maxmech 2600 Watts Angle Grinder.jpeg',       stock:13, active:true, order:16 },
  { id:17, name:'Power Flex 1200W Electric Drill',         brand:'GENERIC', category:'power',       categoryLabel:'POWER TOOLS',          price:22000,  oldPrice:0,      discount:0,  image:'DOMINIC TOOLS/POWER TOOLS/Power Flex Electric Drill 1200 watts.jpeg',   stock:25, active:true, order:17 },
  { id:18, name:'TOTAL 12V Drilling Machine',              brand:'TOTAL',   category:'power',       categoryLabel:'POWER TOOLS',          price:55000,  oldPrice:0,      discount:0,  image:'DOMINIC TOOLS/POWER TOOLS/Total 12V drilling Machine .jpeg',            stock:10, active:true, order:18 },
  { id:19, name:'TOTAL Cordless Angle Grinder',            brand:'TOTAL',   category:'power',       categoryLabel:'POWER TOOLS',          price:68000,  oldPrice:0,      discount:0,  image:'DOMINIC TOOLS/POWER TOOLS/Total Cordless Angle Grinder .jpeg',           stock:7,  active:true, order:19 },
  { id:20, name:'TOTAL 1100W Electric Impact Drill',       brand:'TOTAL',   category:'power',       categoryLabel:'POWER TOOLS',          price:38000,  oldPrice:0,      discount:0,  image:'DOMINIC TOOLS/POWER TOOLS/Total Electric Impact Drill 1100 watts.jpeg',  stock:16, active:true, order:20 },
  { id:21, name:'900W Electric Drill',                     brand:'GENERIC', category:'power',       categoryLabel:'POWER TOOLS',          price:18000,  oldPrice:0,      discount:0,  image:'DOMINIC TOOLS/POWER TOOLS/900W electric drill .png',                   stock:30, active:true, order:21 },
  { id:22, name:'2400W Circular Saw',                      brand:'GENERIC', category:'power',       categoryLabel:'POWER TOOLS',          price:48000,  oldPrice:0,      discount:0,  image:'DOMINIC TOOLS/POWER TOOLS/2400w Circular Saw.png',                     stock:12, active:true, order:22 },
  // ── MECHANIC TOOL KITS ────────────────────────────────────
  { id:23, name:'TOTAL 168 PCS Hand Tools Set',            brand:'TOTAL',   category:'mechanic',    categoryLabel:'MECHANIC TOOL KITS',   price:80000,  oldPrice:0,      discount:0,  image:'DOMINIC TOOLS/PROFESSIONAL TOOL SETS/Total Toolkit .png',               stock:8,  active:true, order:23 },
  { id:24, name:'INGCO 168PCS Hand Tools Set',             brand:'INGCO',   category:'mechanic',    categoryLabel:'MECHANIC TOOL KITS',   price:80000,  oldPrice:0,      discount:0,  image:'DOMINIC TOOLS/PROFESSIONAL TOOL SETS/Ingco set of Handtools.png',       stock:7,  active:true, order:24 },
  { id:25, name:'KingQueen 160 PCS Toolkit',               brand:'GENERIC', category:'mechanic',    categoryLabel:'MECHANIC TOOL KITS',   price:65000,  oldPrice:0,      discount:0,  image:'DOMINIC TOOLS/PROFESSIONAL TOOL SETS/KingQueen 160 pcs Toolkit.jpeg',   stock:10, active:true, order:25 },
  // ── ENGINEERING EQUIPMENT ────────────────────────────────
  { id:26, name:'INGCO 89 in 1 Cordless Drill Tool Set',   brand:'INGCO',   category:'engineering', categoryLabel:'ENGINEERING EQUIPMENT', price:75000,  oldPrice:80000,  discount:6,  image:'DOMINIC TOOLS/PROFESSIONAL TOOL SETS/89 pcs imgco toolbox .png',        stock:6,  active:true, order:26 },
  { id:27, name:'Multifunction Electrical Tool Set',        brand:'GENERIC', category:'engineering', categoryLabel:'ENGINEERING EQUIPMENT', price:50000,  oldPrice:0,      discount:0,  image:'DOMINIC TOOLS/PROFESSIONAL TOOL SETS/Electrical toolkit .png',          stock:15, active:true, order:27 },
  { id:28, name:'DEWALT Professional Toolkit',             brand:'DEWALT',  category:'engineering', categoryLabel:'ENGINEERING EQUIPMENT', price:120000, oldPrice:0,      discount:0,  image:'DOMINIC TOOLS/PROFESSIONAL TOOL SETS/Dewalt toolkit.png',               stock:4,  active:true, order:28 },
  { id:29, name:'18-Piece Holesaw Set',                    brand:'GENERIC', category:'engineering', categoryLabel:'ENGINEERING EQUIPMENT', price:15000,  oldPrice:0,      discount:0,  image:'DOMINIC TOOLS/ACCESSORIES/18pcs set of holesaw.jpeg',                  stock:20, active:true, order:29 },
  // ── HAND TOOLS ────────────────────────────────────────────
  { id:30, name:'TOTAL 8 Inches Plier',                    brand:'TOTAL',   category:'hand',        categoryLabel:'HAND TOOLS',           price:7000,   oldPrice:0,      discount:0,  image:'DOMINIC TOOLS/HAND TOOLS/Total Plier .png',                            stock:25, active:true, order:30 },
  { id:31, name:'TOTAL Combination Plier',                 brand:'TOTAL',   category:'hand',        categoryLabel:'HAND TOOLS',           price:6500,   oldPrice:0,      discount:0,  image:'DOMINIC TOOLS/HAND TOOLS/Total Plier  (1).png',                         stock:20, active:true, order:31 },
  { id:32, name:'INGCO Long Nose Plier',                   brand:'INGCO',   category:'hand',        categoryLabel:'HAND TOOLS',           price:4500,   oldPrice:0,      discount:0,  image:'DOMINIC TOOLS/HAND TOOLS/ingco Long nose Plier .png',                  stock:30, active:true, order:32 },
  { id:33, name:'Harden Crimping Tool',                    brand:'HARDEN',  category:'hand',        categoryLabel:'HAND TOOLS',           price:5000,   oldPrice:0,      discount:0,  image:'DOMINIC TOOLS/HAND TOOLS/Harden Crimping tool .png',                   stock:18, active:true, order:33 },
  { id:34, name:'INGCO Wire Stripper',                     brand:'INGCO',   category:'hand',        categoryLabel:'HAND TOOLS',           price:3500,   oldPrice:0,      discount:0,  image:'DOMINIC TOOLS/HAND TOOLS/ingco wire stripper.png',                     stock:25, active:true, order:34 },
  { id:35, name:'Foldable Wire Stripper',                  brand:'GENERIC', category:'hand',        categoryLabel:'HAND TOOLS',           price:3000,   oldPrice:0,      discount:0,  image:'DOMINIC TOOLS/HAND TOOLS/Foldable Wire Stripper.jpeg',                 stock:15, active:true, order:35 },
  { id:36, name:'INGCO 6-in-1 Screwdrivers',              brand:'INGCO',   category:'hand',        categoryLabel:'HAND TOOLS',           price:4000,   oldPrice:0,      discount:0,  image:'DOMINIC TOOLS/HAND TOOLS/6 in 1 ingco screwdrivers .png',              stock:22, active:true, order:36 },
  { id:37, name:'10-Piece Insulated Screwdriver Set',      brand:'GENERIC', category:'hand',        categoryLabel:'HAND TOOLS',           price:5500,   oldPrice:0,      discount:0,  image:'DOMINIC TOOLS/HAND TOOLS/10upcs insulated set of screwdriver.jpeg',    stock:18, active:true, order:37 },
  { id:38, name:'Insulated Screwdriver Set',               brand:'GENERIC', category:'hand',        categoryLabel:'HAND TOOLS',           price:5000,   oldPrice:0,      discount:0,  image:'DOMINIC TOOLS/HAND TOOLS/Set of Isulated screwdriver.jpeg',            stock:20, active:true, order:38 },
  { id:39, name:'7-Piece Insulated Screwdriver Set',       brand:'GENERIC', category:'hand',        categoryLabel:'HAND TOOLS',           price:4500,   oldPrice:0,      discount:0,  image:'DOMINIC TOOLS/HAND TOOLS/7pcs insulated screwdriver set.jpeg',         stock:15, active:true, order:39 },
  { id:40, name:'8-Piece Screwdriver Set',                 brand:'GENERIC', category:'hand',        categoryLabel:'HAND TOOLS',           price:4000,   oldPrice:0,      discount:0,  image:'DOMINIC TOOLS/HAND TOOLS/8pcs screwdriver set.jpeg',                   stock:25, active:true, order:40 },
  { id:41, name:'Topwin 8-Piece Screwdriver Set',          brand:'TOPWIN',  category:'hand',        categoryLabel:'HAND TOOLS',           price:4200,   oldPrice:0,      discount:0,  image:'DOMINIC TOOLS/HAND TOOLS/8pcs Topwin screwdriver set.jpeg',            stock:18, active:true, order:41 },
  { id:42, name:'6-Piece Screwdriver Set',                 brand:'GENERIC', category:'hand',        categoryLabel:'HAND TOOLS',           price:3500,   oldPrice:0,      discount:0,  image:'DOMINIC TOOLS/HAND TOOLS/6pcs screwdriver set.jpeg',                   stock:20, active:true, order:42 },
];
